/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelling;

import java.util.Random;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author Omar
 */
public class MultipleServerQueue extends javax.swing.JFrame {

    /**
     * Creates new form MultipleServerQueue
     */
    DefaultTableModel model;

    public MultipleServerQueue() {
        initComponents();

        model = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Multiple Server Queue");

        jButton2.setText("Start");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CusNum", "AT", "TB1", "S1", "TE1", "TB2", "S2", "TE2", "TB3", "S3", "TE3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Please enter the number of customers: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)
                                .addGap(99, 99, 99)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 244, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
             Random rand = new Random();
        Scanner sc=new Scanner(System.in);

int Cusnum=Integer.parseInt(jTextField1.getText());

int i ;

int []IAT = new int[Cusnum];
int []AT = new int[Cusnum];
int []ST = new int[Cusnum];


int server1TB[]= new int [Cusnum];
int server2TB[]= new int [Cusnum];
int server3TB[]= new int [Cusnum];

int server1TE[]= new int [Cusnum];
int server2TE[]= new int [Cusnum];
int server3TE[]= new int [Cusnum];

int STserver1[] = new int [Cusnum];
int STserver2[] = new int [Cusnum];
int STserver3[] = new int [Cusnum];

int waiting=0;
int S1Total=0 ;
int S2Total=0 ;
int S3Total=0 ;

int TSTS1 = 0 ;
int TSTS2 = 0 ;
int TSTS3 = 0 ;

float ASTS1 = 0;
float ASTS2 = 0;
float ASTS3 = 0;

int s1cus =0 ;
int s2cus =0 ;
int s3cus =0 ;
    
IAT[0]=0;   
for( i=0 ; i< IAT.length ; i++){
IAT[i]=(int)(Math.random()*10)+1;
}

for( i=0 ; i< AT.length ; i++){
if (i==0){
AT[i] = 0;
}

else{
AT[i] = IAT[i] + AT[i-1] ;
}
}

for( i=0 ; i< ST.length ; i++){
ST[i]=(int)(Math.random()*10)+1;
}


for( i =0 ; i < Cusnum ; i++  ){
    
//  -------- Server1 --------               
if( i == 0 ){
    
server1TB[i]=AT[i];

server1TE[i] = server1TB[i] + ST[i];

STserver1[i] += (server1TE[i] - server1TB[i]);

S1Total+=STserver1[i];

s1cus++;

TSTS1=S1Total;

ASTS1 = TSTS1 /s1cus   ;
}

else if( AT[i] >= server1TE[i-1] ){
    
server1TB[i]=AT[i];

server1TE[i] = server1TB[i] + ST[i];

STserver1[i] += (server1TE[i] - server1TB[i]);

S1Total+=STserver1[i] ;

s1cus++;

TSTS1=S1Total;

ASTS1 = TSTS1 /s1cus   ;
}

//  -------- Server2 --------               

else if( AT[i] < server1TE[i-1]){
    
server2TB[i]=AT[i];

server2TE[i]=server2TB[i]+ST[i];

STserver2[i]+=(server2TE[i] - server2TB[i]);

S2Total += STserver2[i];

s2cus++;

TSTS2 = S2Total;

ASTS2= TSTS2 / s2cus;

}

//  -------- Server3 --------               

else if( AT[i] < server2TE[i-1]   ){
    
server3TB[i] = AT[i];

server3TE[i] = server3TB[i] + ST[i];

STserver3[i] += (server3TE[i] - server3TB[i]);

S3Total += STserver3[i];

s3cus++;

TSTS3=S3Total;

ASTS3=TSTS3/s3cus;
}

//  -------- Waiting --------

else if(AT[i] < server1TE[i-1] && AT[i] < server2TE[i-1] && AT[i] < server3TE[i-1] ){
    
waiting++;

if(AT[i] < server1TE[i-1] ){
server1TB[i]=AT[i];

server1TE[i]= server1TB[i]+ ST[i];

STserver1[i] += (server1TE[i] - server1TB[i]);

S1Total += STserver1[i];

s1cus++;

TSTS1=S1Total;

ASTS1=TSTS1/s1cus;
}

else if(AT[i] < server2TE[i-1] ){
server2TB[i]=AT[i];

server2TE[i]= server2TB[i]+ ST[i];

STserver2[i] += (server2TE[i] - server2TB[i]);

S2Total += STserver2[i];

s2cus++;

TSTS2=S2Total;

ASTS2=TSTS2/s2cus;
}

else if(AT[i] < server3TE[i-1] ){
server3TB[i]=AT[i];

server3TE[i]= server3TB[i]+ ST[i];

STserver3[i] += (server3TE[i] - server3TB[i]);

S3Total += STserver3[i];

s3cus++;

TSTS3=S3Total;

ASTS3=TSTS3/s2cus;
}
}
}


System.out.println();
System.out.println("\t\tServer1\t\t\tServer2\t\t\tServer3");
System.out.println("-----------------------------------------------------------------------------------------------------");
System.out.println("CNum\tAT\tTSBS1\tST\tTSES1\tTSBS2\tST\tTSES2\tTSBS3\tST\tTSES3 ");
System.out.println("-----------------------------------------------------------------------------------------------------");

for(i=0 ; i < Cusnum ; i++ ){
    if((i%Cusnum)==0 && i>0)
    Cusnum++;
model.insertRow(model.getRowCount(),new Object[]{((i%Cusnum)+1) , AT[i] ,server1TB[i], ST[i] ,server1TE[i] , server2TB[i] , ST[i] , server2TE[i] ,server3TB[i],ST[i],server3TE[i]} );
System.out.println(((i%Cusnum)+1)+"\t"+AT[i]+"\t"+server1TB[i]+"\t"+ST[i]+"\t"+server1TE[i]+"\t"+server2TB[i]+"\t"+ST[i]+"\t"+server2TE[i]+"\t"+server3TB[i]+"\t"+ST[i]+"\t"+server3TE[i]);
System.out.println("-----------------------------------------------------------------------------------------------------");
 
}

System.out.println();
System.out.println("Num of Customer S1 = " + s1cus);
System.out.println("Num of Customer S2 = " + s2cus);
System.out.println("Num of Customer S3 = " + s3cus);
System.out.println("-----------------------------------------------------------------------------------------------------");

System.out.println();
System.out.println("Total ST S1 = " + TSTS1);
System.out.println("Total ST S2 = " + TSTS2);
System.out.println("Total ST S3 = " + TSTS3);
System.out.println("-----------------------------------------------------------------------------------------------------");

System.out.println();
System.out.println("AVG ST S1 = " + ASTS1);
System.out.println("AVG ST S2 = " + ASTS2);
System.out.println("AVG ST S3 = " + ASTS3);
System.out.println("-----------------------------------------------------------------------------------------------------");

System.out.println();
System.out.println("Waiting time " + waiting);

        

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new start_page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultipleServerQueue

.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultipleServerQueue

.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultipleServerQueue

.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultipleServerQueue

.class  


.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultipleServerQueue().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}